# SPDX-License-Identifier: APACHE-2.0
services:
  mariadb:
    image: mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin_phpbb
      - MARIADB_DATABASE=phpbb
    volumes:
      - './mariadb_data:/bitnami/mariadb'
  phpbb:
    image: soodrax/phpbb:latest
    ports:
      - '8080:8080'
      - '443:8443'
    environment:
      - PHPBB_DATABASE_HOST=mariadb
      - PHPBB_DATABASE_PORT_NUMBER=3306
      - PHPBB_DATABASE_USER=admin_phpbb
      - PHPBB_DATABASE_NAME=phpbb
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './phpbb_data:/bitnami/phpbb'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phpbb_data:
    driver: local
